### PR TITLE
Use in search the data displayed in the map

### PR DESCRIPTION
**Pull request by lcfd**
And add separators

### CODE REVIEW

**Comment by Piiit** [comment]
@lcfd Thx

**Comment by Piiit** [comment]
@lcfd Is it a work in progress PR?

**Comment by lcfd** [comment]
@Piiit no no, just some fix in dev.
I've waited for a signal to proceed but I have not received any so I've started anyway assuming that was everything alright.

**Comment by Piiit** [comment]
@lcfd Oh sorry, thought I write if I find something that should be fixed, but the other PR was OK... I will open issues on your Kanban if I find problems with the new PRs... hope that is ok?

**Pull request merged**
